# Generated by Django 4.1.3 on 2022-12-10 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_productattributevalue"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAttributeValues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attributevalues",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attributevaluess",
                        to="inventory.productattributevalue",
                    ),
                ),
                (
                    "productinventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attributevaluess",
                        to="inventory.productinventory",
                    ),
                ),
            ],
            options={
                "unique_together": {("attributevalues", "productinventory")},
            },
        ),
        migrations.AddField(
            model_name="productinventory",
            name="attribute_values",
            field=models.ManyToManyField(
                related_name="product_inventory",
                through="inventory.ProductAttributeValues",
                to="inventory.productattributevalue",
            ),
        ),
    ]
