# Generated by Django 4.1.3 on 2022-12-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_producttypeattribute_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                max_length=255, unique=True, verbose_name="category safe URL"
            ),
        ),
    ]
