# Generated by Django 4.1.3 on 2022-12-25 19:30

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_alter_category_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productinventory",
            name="sale_price",
        ),
        migrations.AlterField(
            model_name="productinventory",
            name="retail_price",
            field=models.DecimalField(
                decimal_places=2,
                error_messages={
                    "name": {"max_length": "the price must be between 0 and 999.99"}
                },
                help_text="format: maximum price 999.99",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="product retail price",
            ),
        ),
    ]
