version: "3.8"

services:
  #srv:
  #  container_name: djcommerce
  #  build:
  #    context: .
  #  command: python manage.py loadfixtures && python manage.py runserver 0.0.0.0:8000 && python manage.py search_index --rebuild
  #  networks:
  #    - djangonetwork
  #  volumes:
  #    - .:/usr/src/app
  #  ports:
  #    - 8000:8000
  #  env_file:
  #    - ./dev.env
  #  depends_on:
  #    - pgdb
  #    - redis

  pgdb:
    container_name: pgdb_ecommerce
    image: postgres:15.1-alpine
    restart: always
    ports:
      - 5432:5432
    #env_file:
      #  - ./dev.env
    networks:
      - djangonetwork
    environment:
      - POSTGRES_DB=ecommercev2
      - POSTGERS_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    restart: always
    container_name: redis
    image: redis:7.0.7-alpine
    ports:
      - 6379:6379
  
  celery:
    container_name: celery_djcommerce
    restart: always
    build:
      context: .
    command: celery -A ecommerce worker -l info
    environment:
      - DEBUG=1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/1
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app/

  # celery-beat:
  #   container_name: celery_beat_ecommerce
  #   restart: always
  #   build:
  #     context: .
  #   command: celery -A ecommercev2 beat -l info
  #   depends_on:
  #     - redis
  #     - celery
  #   volumes:
  #     - .:usr/src/app
  
  # flower:
  #   container_name: flower_djcommerce
  #   image: mher/flower
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #   ports:
  #     - 8888:8888
networks:
  djangonetwork:
    driver: bridge
volumes:
  pgdata:
