version: "3.8"

services:
  pgdb:
    container_name: pgdb_ecommerce
    image: postgres:15.1-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=ecommercev2
      - POSTGERS_USER=postgres
      - POSTGRES_PASSWORD=postgres
